### ISSUE TITLE
[Feature] Fill events group information

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/events#11]
# User Story

**As a** event group owner

**I want to** add a description, picture and tags for my events groups

**So that** users will understand the meaning of the group

# Details

- [x] Add the required fields to the event group model (for editing and ownership resolving)
- [x] Develop methods in the repository with permissions check
- [x] Create corresponding routes for the event-groups router
- [ ] Provide the ability to configure permissions (add moderators, transfer ownership)
