### ISSUE TITLE
[Feature] Combine events into groups

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/events#7]
# User Story

**As a** user

**I want to** combine multiple existing events into groups

**So that** I can view custom schedule containing some events

- [ ] Add model for events
- [ ] Create relationship between event group and event models
- [ ] Provide opportunity for owner & moderators of event group to add / remove events from event group
